### PR TITLE
Migrate hyphenate-style-name

### PR DESCRIPTION
**Pull request by TrySound**
Opened pull request

/cc @kof

### CODE REVIEW

**Comment by kof** [comment]
It would be much easier to convert packages which are more complex, because people will see practical benefits and we won't have to deal with rejection that much.

**Comment by kof** [comment]
Also it would be much easier to start with packages which already use rollup. That particular package is so minimalistic, that I think it will be really hard to convince there.

**Comment by kof** [comment]
Another criteria should be a package that is frequently updated.

**Comment by TrySound** [comment]
Yay! First migration in the list.
/cc @kof @Andarist @dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
😱👍

**Pull request merged**
